(()=>{'use strict';
const {S,T,$,$$,esc,save,tasks,doneAll,iso,fmt,daysLeft,reward,NAV,MOBILE,icon,nav,taskRow,trails}=window.G;
const A='assets/blue/';
const pic=(src,alt,cls='')=>`<img class="${cls}" src="${A+src}" alt="${esc(alt)}" decoding="async" loading="eager">`;
const outfitNames=['日常款','学院款','居家款','星空款','节日款'];
const stickerBoard=(limit=8)=>`<div class="stickerGrid">${Array.from({length:Math.min(limit,12)},(_,i)=>`<div class="sticker ${i>=S.stickers.length?'locked':''} s${i%6}"><i></i><span>${esc(S.stickers[i]||'待解锁')}</span></div>`).join('')}</div>`;
const page=(title,desc,body)=>`<div class="page"><header class="pageTitle"><h1>${title}</h1><p>${desc}</p></header>${body}</div>`;
function hero(){const d=new Date(),w=['星期日','星期一','星期二','星期三','星期四','星期五','星期六'][d.getDay()];return `<section class="hero">${pic('hero.webp','蓝紫书桌场景','heroArt')}<div class="heroShade"></div><div class="dateNote"><strong>${d.getMonth()+1}月${d.getDate()}日</strong><span>${w}</span><p>今天也留下一点自己的痕迹。</p></div><div class="heroWhisper"><b>慢一点，</b><span>你已经做得很好了。</span></div></section>`}
function projectGroup(){return `<section class="projects ${S.projectsCollapsed?'closed':''}"><button class="projectsHead" data-project-toggle>${icon('folder')}<span>项目</span>${icon('chevron')}</button><div class="projectsList">${S.plans.map((p,i)=>`<button data-project="${i}" class="${S.selectedProject===p.name?'active':''}"><i></i><span><b>${esc(p.name)}</b><small>${esc(p.area)} · ${p.pct||0}%</small></span><em>${p.pct||0}</em></button>`).join('')}</div></section>`}
function sidebar(){return `<aside class="sidebar"><div class="brand"><div class="brandMark">${icon('collection')}</div><span><b>小小生长册</b><small>Grow with You</small></span><button data-collapse aria-label="折叠侧栏">${S.collapsed?'›':'‹'}</button></div>${nav('sideNav')}${projectGroup()}<div class="sideSignature">${pic('avatar.webp','人物头像')}<p>和更好的自己，<br>一起靠近星光。</p></div></aside>`}
function topbar(){return `<header class="topbar"><button class="mobileProjects" data-mobile-projects>${icon('folder')}<span>项目</span></button><label class="search">${icon('search')}<input id="globalSearch" placeholder="搜索任务、笔记、计划…"></label><div class="topActions"><button class="iconBtn" aria-label="通知">${icon('bell')}</button><div class="wallet"><span><small>金币</small><b>${S.coins}</b></span><span><small>星星</small><b>${S.stars}</b></span></div>${pic('avatar.webp','头像','miniAvatar')}</div></header>`}
function timelineBlock(){const tr=trails();return `<section class="surface timeline"><div class="sectionHead"><h2>今日轨迹</h2><span>${tr.length} 条记录</span></div>${tr.length?tr.map(([ts,t,r])=>`<div class="timelineItem"><time>${new Date(ts).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})}</time><i></i><span>${esc(t)}</span><em>${r}</em></div>`).join(''):'<div class="empty">完成第一件事后，这里会留下今天的轨迹。</div>'}</section>`}
function habitMini(){return `<div class="habitMini">${S.habits.slice(0,5).map(h=>{let s='';for(let i=4;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=iso(d);s+=`<button data-habit="${h.id}" data-date="${k}" class="${h.days?.[k]?'done':''}" aria-label="${esc(h.name)} ${k}"></button>`}return `<div><span>${esc(h.name)}</span><div>${s}</div></div>`}).join('')}</div>`}
function outfits(){return `<div class="outfitStrip">${outfitNames.map((n,i)=>`<button class="${S.selectedOutfit===i?'active':''}" data-outfit="${i}"><i style="--i:${i}"></i><span>${n}</span></button>`).join('')}</div>`}
function scenes(){return `<div class="sceneStrip">${['书房','星空','咖啡店','花园'].map((n,i)=>`<div><i style="--i:${i}"></i><span>${n}</span></div>`).join('')}</div>`}
function today(){const list=tasks(),focus=list.filter(x=>x.focus).slice(0,3),main=focus.length?focus:list.slice(0,3);const growth=[['学习','学习'],['工作','工作'],['写作','写作'],['运动','运动'],['英语','英语']];return `<div class="today">${hero()}<div class="todayPrimary"><section class="surface taskSurface"><div class="sectionHead"><h2>今日重点</h2><span>${list.filter(x=>x.done).length}/${Math.max(list.length,1)} <button class="addBtn" data-add>${icon('plus')}</button></span></div>${main.map(taskRow).join('')||'<div class="empty big">还没有重点任务。<small>添加今天最值得完成的一件事。</small></div>'}<button class="textAction" data-page="inbox">从收集箱整理今天的事</button></section>${timelineBlock()}<section class="surface focusQuick"><div class="sectionHead"><h2>下一件事</h2><span>专注</span></div><div class="nextTask"><b>${esc(list.find(x=>!x.done)?.title||'把这一段时间留给一件事')}</b><small>${list.find(x=>!x.done)?.mins||25} 分钟</small></div><div class="focusClock"><strong id="miniTimer">${fmt(S.timer?.left??1500)}</strong><button class="primary" data-start>开始专注</button></div></section></div><div class="todaySecondary"><section class="surface growth"><div class="sectionHead"><h2>今日成长</h2><span>不比较，只记录</span></div>${growth.map(([label,area],i)=>{const n=list.filter(x=>x.done&&x.area===area).length;return `<div class="growthRow"><span>${label}</span><div><i style="width:${Math.min(100,n*25)}%;--c:${['#6f8ed9','#60b8bd','#8b81d7','#63b69d','#d99aad'][i]}"></i></div><b>${n}</b></div>`}).join('')}</section><section class="surface moodJournal"><div class="moodBlock"><div class="sectionHead"><h2>今日心情</h2></div><div class="moods">${['开心','平静','一般','疲惫','焦虑'].map((n,i)=>`<button data-mood="${i}" class="${S.mood[T]===i?'active':''}"><i></i><span>${n}</span></button>`).join('')}</div></div><div class="journalBlock"><div class="sectionHead"><h2>一句话日记</h2><span>自动保存</span></div><textarea id="journalText" placeholder="今天想留下什么？">${esc(S.journal[T]||'')}</textarea></div></section><section class="surface habitsSurface"><div class="sectionHead"><h2>习惯与倒数</h2><button data-page="habits">查看全部</button></div>${habitMini()}<div class="countdowns">${S.countdowns.slice(0,3).map(c=>`<span><b>${esc(c.name)}</b><em>${daysLeft(c.date)} 天</em></span>`).join('')}</div></section></div><div class="todayArchive"><section class="surface stickersSurface"><div class="sectionHead"><h2>本周贴纸</h2><button data-page="journal">打开手账</button></div>${stickerBoard(8)}</section><section class="surface characterSurface"><div class="sectionHead"><h2>我的小形象</h2><button data-page="collection">去衣橱</button></div>${pic('avatar.webp','人物形象','characterArt')}<p>生活很好，我们慢慢变好。</p></section></div></div>`}
function inbox(){return page('收集箱','先记下来，之后再决定什么时候做。',`<section class="surface pageSurface"><div class="quickInput"><input id="inboxInput" placeholder="突然想到什么？"><button class="primary" data-inbox-add>收下</button></div><div class="simpleList">${S.inbox.map((x,i)=>`<div><span>${esc(x.text)}</span><p><button data-inbox-today="${i}">放到今天</button><button data-inbox-del="${i}">删除</button></p></div>`).join('')||'<div class="empty big">收集箱现在很安静。</div>'}</div></section>`)}
function plans(){const list=S.selectedProject?[...S.plans].sort((a,b)=>(a.name===S.selectedProject?-1:b.name===S.selectedProject?1:0)):S.plans;return page('计划','把长期目标做成可以慢慢写满的成长册。',`<div class="planBooks">${list.map(p=>`<section class="planBook ${p.name===S.selectedProject?'selected':''}"><small>${esc(p.area)}</small><h2>${esc(p.name)}</h2><p>${esc(p.goal)}</p><div class="planMeta"><b>${esc(p.target||'')}</b><span>${p.pct||0}%</span></div><div class="planBar"><i style="width:${p.pct||0}%"></i></div></section>`).join('')}</div>`)}
function calendarPage(){const d=new Date(),y=d.getFullYear(),m=d.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();let cells='';for(let i=0;i<first;i++)cells+='<i></i>';for(let i=1;i<=days;i++){const ds=`${y}-${String(m+1).padStart(2,'0')}-${String(i).padStart(2,'0')}`,n=(S.tasks[ds]||[]).length;cells+=`<button class="${ds===T?'today':''}" data-calendar-date="${ds}"><b>${i}</b>${n?`<span>${n}</span>`:''}</button>`}return page('日历','任务、专注和重要节点放在同一条时间里。',`<section class="surface pageSurface"><div class="calendarHead"><h2>${y}年${m+1}月</h2><span>今天 ${new Date().getDate()} 日</span></div><div class="week">${'日一二三四五六'.split('').map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar">${cells}</div></section><section class="surface dayAgenda"><div class="sectionHead"><h2>今天的安排</h2><button class="addBtn" data-add>${icon('plus')}</button></div>${tasks().map(taskRow).join('')||'<div class="empty">今天还没有安排。</div>'}</section>`)}
function focus(){return page('专注','这一页只留下一件事。',`<section class="focusRoom">${pic('avatar.webp','人物形象','focusCharacter')}<div class="focusPanel"><input id="focusLabel" placeholder="当前任务" value="${esc(S.timer?.label||'')}"><strong id="bigTimer">${fmt(S.timer?.left??1500)}</strong><select id="focusMinutes"><option>25</option><option>45</option><option>60</option></select><div><button class="primary" data-start>开始</button><button class="secondary" data-stop>结束</button></div></div></section>`)}
function habits(){return page('习惯','只记录，不惩罚。',`<div class="habitCards">${S.habits.map(h=>`<section class="surface"><div class="sectionHead"><h2>${esc(h.name)}</h2><span>最近7天</span></div><div class="habitWeek">${Array.from({length:7},(_,j)=>{const d=new Date();d.setDate(d.getDate()-6+j);const ds=iso(d);return `<button data-habit="${h.id}" data-date="${ds}" class="${h.days?.[ds]?'done':''}"><span>${['日','一','二','三','四','五','六'][d.getDay()]}</span></button>`}).join('')}</div></section>`).join('')}</div>`)}
function review(){const m=S.focus.reduce((n,x)=>n+(x.m||0),0);return page('本周复盘','像周记一样回看，而不是看报表。',`<div class="reviewSpread"><section class="surface reviewSummary"><h2>这一周留下了什么</h2><div class="reviewNumbers"><span><b>${doneAll().length}</b>完成任务</span><span><b>${m}</b>专注分钟</span><span><b>${S.stars}</b>累计星星</span></div>${stickerBoard(6)}</section><section class="surface reviewNote"><h2>写给这一周</h2><textarea id="weekNote">${esc(S.weekNote||'')}</textarea></section></div>`)}
function notes(){return page('笔记','学习笔记、灵感和随手记录。',`<button class="primary noteAdd" data-note-add>新笔记</button><div class="notesGrid">${S.notes.map((n,i)=>`<article class="note"><small>${new Date(n.ts).toLocaleDateString('zh-CN')}</small><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p><button data-note-del="${i}">删除</button></article>`).join('')||'<div class="surface empty big">还没有笔记。</div>'}</div>`)}
function journal(){const d=new Date();return page('手账','把现实里的努力慢慢变成可以收藏的页面。',`<div class="journalSpread"><section class="surface stickerPage"><div class="sectionHead"><h2>${d.getMonth()+1}月贴纸页</h2><span>${S.stickers.length}/12</span></div>${stickerBoard(12)}</section><section class="monthlyMemory"><small>MONTHLY MEMORY</small><h2>${d.getFullYear()} · ${d.getMonth()+1}月</h2><p>完成 ${doneAll().length} 件现实任务<br>累计 ${S.stars} 颗星星</p><blockquote>认真做事，好好生活。<br>这一页会一直留在这里。</blockquote></section></div>`)}
function collection(){return page('收藏','衣橱、贴纸、徽章和场景都在这里慢慢累积。',`<div class="collectionLayout"><section class="wardrobe">${pic('avatar.webp','当前人物','wardrobeCharacter')}<div><div class="sectionHead"><h2>我的衣橱</h2><span>${outfitNames[S.selectedOutfit]}</span></div>${outfits()}</div></section><section class="surface stickerPage"><div class="sectionHead"><h2>手账贴纸册</h2><span>${S.stickers.length}/12</span></div>${stickerBoard(12)}</section><section class="surface"><div class="sectionHead"><h2>成长徽章</h2><span>部分隐藏</span></div><div class="badges"><span class="earned">第一次专注</span><span class="${doneAll().length>=10?'earned':''}">完成10件事</span><span class="${S.stickers.length>=6?'earned':''}">收集6枚贴纸</span></div></section><section class="surface"><div class="sectionHead"><h2>场景收藏</h2></div>${scenes()}</section></div>`)}
const pages={today,inbox,plans,calendar:calendarPage,focus,habits,review,notes,journal,collection};
function shell(){const mobile=NAV.filter(([k])=>MOBILE.includes(k));return `<div class="app ${S.collapsed?'collapsed':''}"><div class="drawerScrim" data-drawer-close></div>${sidebar()}<main>${topbar()}<section id="view">${(pages[S.page]||today)()}</section></main>${nav('mobileNav',mobile)}<button class="fab" data-add aria-label="快速添加">${icon('plus')}</button></div>`}
let tick;
function render(){clearInterval(tick);$('#app').innerHTML=shell();bind();if(S.timer)runTick()}
function bind(){$$('[data-page]').forEach(b=>b.onclick=()=>{S.page=b.dataset.page;document.querySelector('.app')?.classList.remove('drawerOpen');save();render()});$('[data-collapse]')?.addEventListener('click',()=>{S.collapsed=!S.collapsed;save();render()});$('[data-project-toggle]')?.addEventListener('click',()=>{S.projectsCollapsed=!S.projectsCollapsed;save();render()});$('[data-mobile-projects]')?.addEventListener('click',()=>document.querySelector('.app')?.classList.add('drawerOpen'));$('[data-drawer-close]')?.addEventListener('click',()=>document.querySelector('.app')?.classList.remove('drawerOpen'));$$('[data-project]').forEach(b=>b.onclick=()=>{const p=S.plans[+b.dataset.project];if(!p)return;S.selectedProject=p.name;S.page='plans';save();render()});$$('[data-toggle]').forEach(b=>b.onclick=()=>{const x=tasks().find(t=>String(t.id)===b.dataset.toggle);if(!x)return;x.done=!x.done;x.doneAt=x.done?Date.now():null;if(x.done)reward(x.reward||10);save();render()});$$('[data-add]').forEach(b=>b.onclick=addTask);$$('[data-mood]').forEach(b=>b.onclick=()=>{S.mood[T]=+b.dataset.mood;save();render()});$('#journalText')?.addEventListener('input',e=>{S.journal[T]=e.target.value;save()});$('#weekNote')?.addEventListener('input',e=>{S.weekNote=e.target.value;save()});$$('[data-habit]').forEach(b=>b.onclick=()=>{const h=S.habits.find(x=>x.id===b.dataset.habit);if(!h)return;h.days=h.days||{};h.days[b.dataset.date]=!h.days[b.dataset.date];save();render()});$$('[data-outfit]').forEach(b=>b.onclick=()=>{S.selectedOutfit=+b.dataset.outfit;save();render()});$('[data-inbox-add]')?.addEventListener('click',()=>{const i=$('#inboxInput');const text=i?.value.trim();if(!text)return;S.inbox.push({text,ts:Date.now()});save();render()});$$('[data-inbox-del]').forEach(b=>b.onclick=()=>{S.inbox.splice(+b.dataset.inboxDel,1);save();render()});$$('[data-inbox-today]').forEach(b=>b.onclick=()=>{const x=S.inbox.splice(+b.dataset.inboxToday,1)[0];if(x)tasks().push({id:Date.now(),title:x.text,area:'生活',mins:25,reward:10,done:false});save();render()});$('[data-note-add]')?.addEventListener('click',()=>{const title=prompt('笔记标题');if(!title)return;const text=prompt('写点什么？')||'';S.notes.unshift({title,text,ts:Date.now()});save();render()});$$('[data-note-del]').forEach(b=>b.onclick=()=>{S.notes.splice(+b.dataset.noteDel,1);save();render()});$$('[data-start]').forEach(b=>b.onclick=startTimer);$$('[data-stop]').forEach(b=>b.onclick=stopTimer)}
function addTask(){const title=prompt('今天想完成什么？');if(!title)return;const mins=+(prompt('预计多少分钟？','25')||25);const area=prompt('成长领域：学习 / 工作 / 写作 / 运动 / 英语 / 生活','学习')||'生活';tasks().push({id:Date.now(),title,mins,area,reward:10,done:false,focus:tasks().length<3});save();render()}
function startTimer(){if(S.timer)return;const mins=+($('#focusMinutes')?.value||25);const label=$('#focusLabel')?.value.trim()||tasks().find(x=>!x.done)?.title||'专注';S.timer={left:mins*60,total:mins*60,label,started:Date.now()};save();render()}
function stopTimer(){if(!S.timer)return;const spent=Math.max(1,Math.round((S.timer.total-S.timer.left)/60));S.focus.push({date:T,m:spent,ts:Date.now(),label:S.timer.label});reward(8);S.timer=null;save();render()}
function runTick(){tick=setInterval(()=>{if(!S.timer)return;S.timer.left=Math.max(0,S.timer.left-1);const v=fmt(S.timer.left),a=$('#miniTimer'),b=$('#bigTimer');if(a)a.textContent=v;if(b)b.textContent=v;if(S.timer.left<=0){stopTimer()}else if(S.timer.left%10===0)save()},1000)}
render();
})();