const planMethods=[
 {id:'sprint',name:'12周成果冲刺',desc:'适合考证、求职和小说等有明确交付物的主线。',days:84,freq:6,color:'#c8b7f2'},
 {id:'woop',name:'WOOP障碍计划',desc:'先识别真实障碍，再写好状态不好时的替代动作。',days:30,freq:5,color:'#f3bdd2'},
 {id:'habit',name:'66天习惯养成',desc:'固定触发场景，关注持续出现，不要求每天满分。',days:66,freq:5,color:'#b9d9d0'},
 {id:'exam',name:'考试倒推计划',desc:'从考试日倒排章节、刷题、模考与查漏阶段。',days:84,freq:6,color:'#b9cdf3'},
 {id:'minimum',name:'最低行动线',desc:'标准版和五分钟保底版并存，状态差也不脱轨。',days:30,freq:7,color:'#f3d8a8'},
 {id:'input',name:'输入—输出闭环',desc:'英语与播客采用输入、摘记、复述、应用四步。',days:30,freq:4,color:'#bfc9f1'},
 {id:'creative',name:'作品资产计划',desc:'按周累计字数、章节状态与存稿，不强迫均匀日更。',days:84,freq:5,color:'#e6bddf'},
 {id:'custom',name:'完全自定义',desc:'自己决定周期、频率、成果、标准动作与保底动作。',days:30,freq:3,color:'#cbd3e9'}
];
D.plans=D.plans||[];D.game=D.game||{outfit:0,theme:'starlight'};let selectedPlanMethod='sprint';
function renderPlanTemplates(){if(!$('planTemplates'))return;$('planTemplates').innerHTML=planMethods.map(m=>'<button class="planTemplate '+(m.id===selectedPlanMethod?'selected':'')+'" style="--orb:'+m.color+'" data-method="'+m.id+'"><b>'+m.name+'</b><small>'+m.desc+'</small></button>').join('');document.querySelectorAll('[data-method]').forEach(b=>b.onclick=()=>{selectedPlanMethod=b.dataset.method;let m=planMethods.find(x=>x.id===selectedPlanMethod);$('planMethod').value=m.id;$('planDays').value=String(m.days);$('planFreq').value=String(m.freq);renderPlanTemplates()})}
$('planMethod').innerHTML=planMethods.map(m=>'<option value="'+m.id+'">'+m.name+'</option>').join('');
$('planMethod').onchange=e=>{selectedPlanMethod=e.target.value;renderPlanTemplates()};
$('planForm').onsubmit=e=>{e.preventDefault();D.plans.unshift({id:Date.now(),name:$('planName').value.trim(),category:$('planCategory').value,method:$('planMethod').value,days:+$('planDays').value,freq:+$('planFreq').value,outcome:$('planOutcome').value.trim(),action:$('planAction').value.trim(),minimum:$('planMinimum').value.trim(),fallback:$('planFallback').value.trim(),start:TODAY,done:0,logs:[]});$('planForm').reset();selectedPlanMethod='sprint';save();toast('计划已经启航')};
function tickPlan(id,minimum=false){let p=D.plans.find(x=>x.id===id);if(!p)return;if(p.logs.some(x=>x.date===TODAY))return toast('今天已经给这个计划点亮过星星了');p.logs.push({date:TODAY,minimum});p.done++;reward(minimum?5:12,minimum?2:6,'plan-'+TODAY+'-'+id);save()}
function deletePlan(id){if(confirm('删除这个计划吗？')){D.plans=D.plans.filter(x=>x.id!==id);save()}}
function renderPlans(){renderPlanTemplates();if(!$('activePlans'))return;$('activePlans').innerHTML=D.plans.map(p=>{let target=Math.max(1,Math.ceil(p.days/7*p.freq)),pct=Math.min(100,Math.round(p.done/target*100)),m=planMethods.find(x=>x.id===p.method),todayDone=p.logs.some(x=>x.date===TODAY);return '<article class="activePlan"><div class="activePlanHead"><div><b>'+esc(p.name)+'</b><small>'+esc(p.category)+' · '+(m?m.name:'自定义')+'</small></div><b>'+pct+'%</b></div><div class="meter"><i style="width:'+pct+'%"></i></div><p><strong>本次行动：</strong>'+esc(p.action)+'</p><small>最低线：'+esc(p.minimum)+'</small>'+(p.fallback?'<small>预案：'+esc(p.fallback)+'</small>':'')+'<div class="activePlanActions"><button '+(todayDone?'disabled':'')+' onclick="tickPlan('+p.id+',false)">'+(todayDone?'今日已完成':'完成标准行动')+'</button><button '+(todayDone?'disabled':'')+' onclick="tickPlan('+p.id+',true)">只做最低线</button><button class="quietDanger" onclick="deletePlan('+p.id+')">删除</button></div></article>'}).join('')||'<div class="empty">选择上面的模板，创建第一条真正可执行的计划。</div>'}

function gameIcon(name){const paths={
 back:'<path d="M18 5 7 16l11 11" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><path d="M8 16h19" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/>',
 map:'<path d="M4 8l8-4 8 4 8-4v20l-8 4-8-4-8 4z" fill="#e6dcff" stroke="currentColor" stroke-width="1.5"/><path d="M12 4v20M20 8v20" fill="none" stroke="#947bd2" stroke-width="1.5"/><path d="M22 13c0 3-3 5-3 5s-3-2-3-5a3 3 0 1 1 6 0z" fill="#f5c4db"/>',
 decor:'<path d="M6 17h20v9H6z" fill="#d9cdf8" stroke="currentColor" stroke-width="1.5"/><path d="M8 17v-4a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v4" fill="#f7d5e6" stroke="currentColor" stroke-width="1.5"/><path d="M5 12h4v10H5zM23 12h4v10H5z" fill="#fff1bd" stroke="currentColor" stroke-width="1.5"/>',
 wardrobe:'<path d="M16 7a4 4 0 1 0-4-4" fill="none" stroke="currentColor" stroke-width="2"/><path d="M16 7 5 15h22z" fill="#e9ddff" stroke="currentColor" stroke-width="1.5"/><path d="M7 15v12h18V15" fill="#bca7eb" stroke="currentColor" stroke-width="1.5"/><path d="m16 13 2 4 4 .5-3 3 .8 4.2-3.8-2-3.8 2 .8-4.2-3-3 4-.5z" fill="#ffe49b"/>',
 pet:'<path d="M9 12C5 8 6 3 9 3c3 0 4 5 4 8M23 12c4-4 3-9 0-9-3 0-4 5-4 8" fill="#f6d9e9" stroke="currentColor" stroke-width="1.5"/><ellipse cx="16" cy="19" rx="10" ry="8" fill="#fff" stroke="currentColor" stroke-width="1.5"/><circle cx="12" cy="18" r="1.3"/><circle cx="20" cy="18" r="1.3"/><path d="M14 22q2 2 4 0" fill="none" stroke="#d58aa9" stroke-width="1.5"/>',
 shop:'<path d="M7 12h18l-2 16H9z" fill="#e0d3fa" stroke="currentColor" stroke-width="1.5"/><path d="M11 13V9a5 5 0 0 1 10 0v4" fill="none" stroke="#8c75c7" stroke-width="2"/><path d="m16 17 1.5 3 3.5.5-2.5 2.4.6 3.4-3.1-1.6-3.1 1.6.6-3.4-2.5-2.4 3.5-.5z" fill="#ffe19a"/>',
 bag:'<path d="M5 10h22v18H5z" rx="3" fill="#d8e4ff" stroke="currentColor" stroke-width="1.5"/><path d="M11 10V7h10v3M5 16h22" fill="none" stroke="#8c75c7" stroke-width="1.5"/><circle cx="16" cy="19" r="2" fill="#ffe19a"/>',
 award:'<path d="m16 3 3 6 7 .9-5 4.8 1.3 6.8L16 18l-6.3 3.5 1.3-6.8-5-4.8L13 9z" fill="#ffe19a" stroke="currentColor" stroke-width="1.5"/><path d="m11 20-2 9 7-4 7 4-2-9" fill="#c6b3ef" stroke="currentColor" stroke-width="1.5"/>',
 coin:'<circle cx="16" cy="16" r="12" fill="#ffd873" stroke="#fff2b8" stroke-width="2"/><path d="m16 8 2.4 4.8 5.3.8-3.8 3.7.9 5.2-4.8-2.5-4.8 2.5.9-5.2-3.8-3.7 5.3-.8z" fill="#fff2b8"/>',
 dust:'<path d="M9 9h14l-2 18H11z" fill="#b9b4f4" stroke="#fff" stroke-width="1.5"/><path d="M8 6h16v4H8z" fill="#ffe4a4"/><circle cx="14" cy="17" r="2" fill="#fff"/><path d="m20 15 1 2 2 .3-1.5 1.4.4 2-1.9-1-1.9 1 .4-2-1.5-1.4 2-.3z" fill="#fff0a7"/>'
};return '<svg viewBox="0 0 32 32" aria-hidden="true">'+paths[name]+'</svg>'}
function itemIcon(type){const p={sofa:'<path d="M5 17h22v9H5zM7 17v-5q0-4 4-4h10q4 0 4 4v5"/><path d="M4 14h5v8H4zm19 0h5v8h-5z"/>',table:'<path d="M6 12h20v6H6zM10 18v9m12-9v9"/>',rug:'<ellipse cx="16" cy="20" rx="12" ry="7"/><path d="m16 10 2 4 4 .6-3 3 .7 4-3.7-2-3.7 2 .7-4-3-3 4-.6z"/>',pet:'<path d="M9 12C6 8 7 4 10 4c2 0 3 4 3 7m10 1c3-4 2-8-1-8-2 0-3 4-3 7"/><path d="M7 16h18v11H7z"/><circle cx="12" cy="20" r="1"/><circle cx="20" cy="20" r="1"/>',bed:'<path d="M4 19h24v8H4zM7 19V9h17q4 0 4 4v6M4 13h9v6"/>',desk:'<path d="M5 13h22v5H5zM9 18v10m14-10v10M12 8h8v5h-8z"/>',shelf:'<path d="M7 4h18v24H7zM7 12h18M7 20h18"/><path d="M10 7h2v4h-2zm5 0h2v4h-2zm4 8h3v4h-3z"/>',lamp:'<path d="M16 6v7m-6 4h12l-3-5h-6zM16 17v9m-5 2h10"/>',flower:'<path d="M16 15v13M10 28h12l-2-7h-8z"/><circle cx="16" cy="9" r="4"/><circle cx="11" cy="10" r="3"/><circle cx="21" cy="10" r="3"/>'};return '<svg class="itemSvg" viewBox="0 0 32 32" aria-hidden="true">'+p[type]+'</svg>'}

const gameHud=document.createElement('div');gameHud.className='gameHud';gameHud.innerHTML='<button class="gameBack" aria-label="返回工作台">'+gameIcon('back')+'</button><div class="roomLabel" id="roomLabel">星月洋馆</div><div class="currencyBar"><div class="currencyPill">'+gameIcon('coin')+'<span id="hudCoins">0</span></div><div class="currencyPill">'+gameIcon('dust')+'<span id="hudDust">0</span></div></div>';document.body.appendChild(gameHud);
const dockItems=[['map','地图'],['decor','装修'],['wardrobe','衣橱'],['pet','兔兔'],['shop','商城'],['bag','仓库'],['award','成就']];
const gameDock=document.createElement('div');gameDock.className='gameDock';gameDock.innerHTML=dockItems.map(x=>'<button class="dockButton" data-panel="'+x[0]+'">'+gameIcon(x[0])+'<span>'+x[1]+'</span></button>').join('');document.body.appendChild(gameDock);
const sheet=document.createElement('div');sheet.className='gameSheet';sheet.innerHTML='<div class="sheetHead"><div><small class="sheetEyebrow">STARLIGHT HOME</small><h3 id="sheetTitle">星月家园</h3></div><button class="sheetClose" aria-label="关闭">×</button></div><div id="sheetBody"></div>';document.body.appendChild(sheet);sheet.querySelector('.sheetClose').onclick=()=>sheet.classList.remove('open');
const baseGotoPage=gotoPage;
function enterGame(){document.body.classList.add('game-mode');renderHouse();renderGameHud()}
function leaveGame(){document.body.classList.remove('game-mode');sheet.classList.remove('open');baseGotoPage('home')}
gameHud.querySelector('.gameBack').onclick=leaveGame;
gotoPage=function(id){baseGotoPage(id);if(id==='game')enterGame();else document.body.classList.remove('game-mode');if(id==='plans'){$('pageTitle').textContent='把愿望变成可执行的航线';renderPlans()}};
function renderGameHud(){if(!$('hudCoins'))return;$('hudCoins').textContent=D.coins;$('hudDust').textContent=Math.floor(D.xp/10);$('roomLabel').textContent={exterior:'星月洋馆',living:'一层 · 星光客厅',bedroom:'二层 · 月光卧室',bunny:'兔兔房'}[D.house.room]||'星月洋馆'}
function changeRoom(room){openRoom(room);sheet.classList.remove('open');renderGameHud()}
function roomButtons(){let rooms=[['living','星光客厅','一层会客与休息区'],['bedroom','月光卧室','二层睡眠与换装区'],['bunny','兔兔房','陪伴、喂食与收藏'],['garden','星梦花园','下一阶段解锁']];return '<div class="roomGrid">'+rooms.map((r,i)=>'<button class="roomCard roomCard'+i+'" onclick="changeRoom(\''+r[0]+'\')" '+(r[0]==='garden'?'disabled':'')+'><span>'+itemIcon(i===0?'sofa':i===1?'bed':i===2?'pet':'flower')+'</span><b>'+r[1]+'</b><small>'+r[2]+'</small></button>').join('')+'</div>'}
const decorCatalog=[['云朵沙发','cloud-sofa',80],['星星茶几','star-table',60],['月亮地毯','moon-rug',50],['兔兔小窝','bunny-bed',70],['月光床','moon-canopy',130],['贝壳床','shell-daybed',150],['星象书桌','astronomy-desk',120],['拱门书架','arched-shelf',100],['月光衣柜','celestial-wardrobe',180],['星尘梳妆台','vanity',160],['星星落地灯','star-lamp',75],['月光花','moon-flower',65]];
function placeDecor(name){let room=D.game?.decorRoom||D.house.room;if(room==='exterior')room='living';let active=D.house.rooms[room]||(D.house.rooms[room]=[]),rule=furnitureRules[name];if(!D.house.ownedFurniture.includes(name))return toast('请先到家具商城购买');if(rule&&!rule.rooms.includes(room))return toast('这件家具不适合当前房间');let at=active.indexOf(name);if(at>=0)active.splice(at,1);else{if(rule)active=D.house.rooms[room]=active.filter(x=>!furnitureRules[x]||furnitureRules[x].slot!==rule.slot);active.push(name)}save();renderHouse();if(window.renderGameV5)window.renderGameV5();toast(at>=0?'家具已收回仓库':'家具已放到预设位置')}
function buyFurniture(name,cost){if(D.house.ownedFurniture.includes(name))return toast('已经拥有这件家具');if(D.coins<cost)return toast('金币还不够，先完成现实任务');D.coins-=cost;D.house.ownedFurniture.push(name);save();renderPanel('furnitureStore');toast('家具已送入仓库')}
function catalogFurniture(mode='editor'){let room=mode==='editor'?(D.game?.decorRoom||D.house.room):D.house.room;if(room==='exterior')room='living';let active=D.house.rooms[room]||[],owned=decorCatalog.filter(x=>D.house.ownedFurniture.includes(x[0])),list=mode==='store'?decorCatalog:mode==='editor'?owned.filter(x=>!furnitureRules[x[0]]||furnitureRules[x[0]].rooms.includes(room)):owned;return '<div class="sheetTabs"><button class="active">全部</button><button>座椅</button><button>桌柜</button><button>床具</button><button>灯饰</button><button>兔兔用品</button></div><div class="catalogGrid">'+list.map(f=>{let has=D.house.ownedFurniture.includes(f[0]),placed=active.includes(f[0]),action=mode==='store'?(has?'已拥有':'购买 '+f[2]+' 金币'):mode==='inventory'?'已收藏':(placed?'收回仓库':'预览摆放'),handler=mode==='store'?"buyFurniture('"+f[0]+"',"+f[2]+")":mode==='inventory'?"":"placeDecor('"+f[0]+"')";return '<article class="catalogCard"><div class="itemArt"><img loading="lazy" decoding="async" src="assets/furniture/'+f[1]+'.webp?v=7" alt="'+f[0]+'"></div><b>'+f[0]+'</b><small>'+(has?(placed?'当前房间已摆放':'已拥有'):f[2]+'金币')+'</small>'+(mode==='inventory'?'<span class="inventoryTag">已收藏</span>':'<button '+(mode==='store'&&has?'disabled':'')+' onclick="'+handler+'">'+action+'</button>')+'</article>'}).join('')+'</div>'+(list.length?'':'<div class="empty">'+(mode==='editor'?'这个房间还没有适配的家具，请先去家具商城购买。':'仓库里还没有家具，请先去家具商城购买。')+'</div>')}
const outfits=[['月华云梦',0],['青岚花信',1],['星夜王庭',2],['白金礼装',3],['兔兔烘焙',4],['烟火和风',5],['紫雾旅拍',6],['夜幕绅士',7]];
function chooseOutfit(i){let name=outfits[i][0];if(!D.owned.includes(name)&&i!==0)return toast('这套服装尚未拥有，请前往服饰商城');D.game.outfit=i;D.equipped=name;save();renderPanel('wardrobe')}
function buyOutfit(i){let name=outfits[i][0],cost=i===0?0:120+i*25;if(D.owned.includes(name)||i===0)return toast('已经拥有这套服装');if(D.coins<cost)return toast('这套服装需要 '+cost+' 金币');D.coins-=cost;D.owned.push(name);save();renderPanel('clothingStore');toast('服装已送入衣橱')}
function wardrobePanel(){let ownedIndexes=outfits.map((x,i)=>({x,i})).filter(v=>v.i===0||D.owned.includes(v.x[0])),pos=(D.game.outfit%4*33.333)+'% '+(Math.floor(D.game.outfit/4)*100)+'%';return '<div class="wardrobeStage"><div class="avatarShowcase"><div class="avatarLarge" style="background-position:'+pos+'"></div><div class="outfitTitle"><small>当前穿搭</small><b>'+esc(D.equipped)+'</b></div></div><div class="wardrobeRack"><div class="sheetTabs"><button class="active">套装</button><button>发型</button><button>上装</button><button>下装</button><button>鞋履</button><button>头饰</button><button>配饰</button></div><p class="hint">衣橱只展示已拥有物品；购买请前往服饰商城。</p><div class="wardrobeList">'+ownedIndexes.map(v=>{let p=(v.i%4*33.333)+'% '+(Math.floor(v.i/4)*100)+'%';return '<button class="outfitCard '+(D.game.outfit===v.i?'selected':'')+'" onclick="chooseOutfit('+v.i+')"><span style="background-position:'+p+'"></span><b>'+v.x[0]+'</b><small>已拥有 · 点击试穿</small></button>'}).join('')+'</div></div></div>'}
function clothingStore(){return '<div class="sheetTabs"><button class="active">套装</button><button>发型</button><button>上装</button><button>下装</button><button>鞋履</button><button>配饰</button></div><div class="wardrobeList">'+outfits.map((x,i)=>{let p=(i%4*33.333)+'% '+(Math.floor(i/4)*100)+'%',has=i===0||D.owned.includes(x[0]),cost=i===0?0:120+i*25;return '<article class="outfitCard"><span style="background-position:'+p+'"></span><b>'+x[0]+'</b><small>'+(has?'已拥有':cost+'金币')+'</small><button '+(has?'disabled':'')+' onclick="buyOutfit('+i+')">'+(has?'已拥有':'购买')+'</button></article>'}).join('')+'</div>'}
function petPanel(){return '<div class="petPanel"><div class="petPortrait"></div><div class="petStatus"><h3>月绒兔小档案</h3><div><span>亲密度 <b>'+D.house.love+'</b></span><span>饱腹度 <b>'+D.house.food+'%</b></span></div><p>现实里的持续打卡会让它长大；照顾兔兔只提供小奖励，不制造额外负担。</p><div class="petActions"><button onclick="petAction(\'feed\')">喂胡萝卜</button><button onclick="petAction(\'play\')">陪它玩</button><button onclick="petAction(\'sleep\')">哄它睡觉</button><button onclick="petAction(\'study\')">陪你读书</button></div></div></div>'}
function achievementPanel(){let checks=[['初见星光','完成第1次打卡',D.checkins.length>=1],['专注猎人','完成10个番茄',D.focus.length>=10],['十万字宇宙','小说达到10万字',D.words>=100000],['百日同轨','累计打卡100天',D.checkins.length>=100],['知识星舰','学习100小时',D.study.reduce((s,x)=>s+x.m,0)>=6000],['衣橱收藏家','拥有5套装扮',D.owned.length>=5]];return '<div class="achievementGrid">'+checks.map(x=>'<article class="achievementCard '+(x[2]?'unlocked':'')+'">'+gameIcon('award')+'<b>'+x[0]+'</b><small>'+x[1]+'</small></article>').join('')+'</div>'}
function renderPanel(type){let map={map:['家园地图',roomButtons()],decor:['房间装修',catalogFurniture('editor')],wardrobe:['星回衣橱',wardrobePanel()],pet:['兔兔小屋',petPanel()],shop:['星光商城','<div class="shopGate"><button onclick="renderPanel(\'furnitureStore\')">'+gameIcon('decor')+'<b>家具商城</b><small>购买家具、灯饰与房间套装</small></button><button onclick="renderPanel(\'clothingStore\')">'+gameIcon('wardrobe')+'<b>服饰商城</b><small>购买服装、发型、鞋履与配饰</small></button></div>'],furnitureStore:['家具商城',catalogFurniture('store')],clothingStore:['服饰商城',clothingStore()],bag:['我的仓库','<div class="inventorySummary"><span>家具 <b>'+D.house.ownedFurniture.length+'</b></span><span>服装 <b>'+D.owned.length+'</b></span></div>'+catalogFurniture('inventory')],award:['成就图鉴',achievementPanel()]};$('sheetTitle').textContent=map[type][0];$('sheetBody').innerHTML=map[type][1];sheet.classList.add('open');gameDock.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===type))}
gameDock.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>renderPanel(b.dataset.panel));
const oldRenderAllV4=renderAll;renderAll=function(){oldRenderAllV4();renderPlans();renderGameHud()};renderPlans();renderGameHud();
