const decorAssets={'云朵沙发':'cloud-sofa','星星茶几':'star-table','月亮地毯':'moon-rug','兔兔小窝':'bunny-bed','月光床':'moon-canopy','贝壳床':'shell-daybed','星象书桌':'astronomy-desk','拱门书架':'arched-shelf','星星灯':'star-lamp','星星落地灯':'star-lamp','月光花':'moon-flower'};
const furnitureLayer=document.createElement('div');furnitureLayer.className='furnitureLayer';$('houseStage').prepend(furnitureLayer);
function openRoom(room){if(room==='garden')return toast('花园正在生长，下一阶段开放');D.house.room=room;renderHouse();localStorage.setItem(KEY,JSON.stringify(D))}
function backHome(){D.house.room='exterior';renderHouse();localStorage.setItem(KEY,JSON.stringify(D))}
document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>openRoom(b.dataset.room));
$('backHome').onclick=backHome;
function petAction(action){if(action==='feed'&&D.coins<3)return toast('需要3金币购买胡萝卜');if(action==='feed'){D.coins-=3;D.house.food=Math.min(100,D.house.food+20);D.house.love+=2;D.house.petPose=4}else if(action==='play'){D.house.love+=3;D.house.food=Math.max(0,D.house.food-5);D.house.petPose=6}else if(action==='sleep'){D.house.petPose=3;D.house.food=Math.max(0,D.house.food-2)}else{D.house.love+=2;D.house.petPose=2}save()}
document.querySelectorAll('[data-pet]').forEach(b=>b.onclick=()=>petAction(b.dataset.pet));
function renderHouse(){let exterior=D.house.room==='exterior',room=exterior?'living':D.house.room;$('homeExterior').hidden=!exterior;$('roomView').hidden=exterior;$('houseStage').className='houseStage card '+(exterior?'exteriorRoom':room==='bedroom'?'floor2':room==='bunny'?'bunnyRoom':'floor1');document.querySelectorAll('.floorTabs [data-room]').forEach(b=>b.classList.toggle('active',b.dataset.room===room));$('petLove').textContent=D.house.love;$('petFood').textContent=D.house.food;$('slotA').hidden=true;$('slotB').hidden=true;$('characterArt').hidden=true;let active=D.house.rooms[room]||[];furnitureLayer.innerHTML=exterior?'':active.slice(0,6).map((name,i)=>decorAssets[name]?'<img class="placedFurniture placed'+i+'" alt="'+name+'" src="assets/furniture/'+decorAssets[name]+'.webp" decoding="async">':'').join('');$('furnitureShop').innerHTML='<div class="empty">高清家具已移入沉浸式游戏商城。</div>'}
const oldRenderAll=renderAll;renderAll=function(){oldRenderAll();renderHouse()};renderHouse();
