const furnitureItems=[['云朵沙发',1,0,80],['星星茶几',2,0,60],['月亮地毯',3,0,50],['兔兔小窝',1,1,70],['月光床',2,1,130],['贝壳床',3,1,150],['星象书桌',0,2,120],['拱门书架',1,2,100],['星星落地灯',2,2,75],['月光花',3,2,65]];
function spritePos(x,y){return (x*33.333)+'% '+(y*50)+'%'}
function openRoom(room){if(room==='garden')return toast('花园正在生长，下一阶段开放');D.house.room=room;renderHouse();localStorage.setItem(KEY,JSON.stringify(D))}
function backHome(){D.house.room='exterior';renderHouse();localStorage.setItem(KEY,JSON.stringify(D))}
document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>openRoom(b.dataset.room));
$('backHome').onclick=backHome;
function petAction(action){if(action==='feed'&&D.coins<3)return toast('需要3金币购买胡萝卜');if(action==='feed'){D.coins-=3;D.house.food=Math.min(100,D.house.food+20);D.house.love+=2;D.house.petPose=4}else if(action==='play'){D.house.love+=3;D.house.food=Math.max(0,D.house.food-5);D.house.petPose=6}else if(action==='sleep'){D.house.petPose=3;D.house.food=Math.max(0,D.house.food-2)}else{D.house.love+=2;D.house.petPose=2}save()}
document.querySelectorAll('[data-pet]').forEach(b=>b.onclick=()=>petAction(b.dataset.pet));
function equipFurniture(name){let room=D.house.room||'living',active=D.house.rooms[room]||(D.house.rooms[room]=[]),item=furnitureItems.find(x=>x[0]===name);if(!D.house.ownedFurniture.includes(name)){if(D.coins<item[3])return toast('金币还不够');D.coins-=item[3];D.house.ownedFurniture.push(name)}if(active.includes(name))active.splice(active.indexOf(name),1);else{if(active.length>=2)active.shift();active.push(name)}save()}
function renderHouse(){let room=D.house.room==='exterior'?'living':D.house.room;$('homeExterior').hidden=D.house.room!=='exterior';$('roomView').hidden=D.house.room==='exterior';$('houseStage').className='houseStage card '+(room==='bedroom'?'floor2':room==='bunny'?'bunnyRoom':'floor1');document.querySelectorAll('.floorTabs [data-room]').forEach(b=>b.classList.toggle('active',b.dataset.room===room));$('petLove').textContent=D.house.love;$('petFood').textContent=D.house.food;$('houseBunny').style.backgroundPosition=(D.house.petPose%4*33.333)+'% '+(Math.floor(D.house.petPose/4)*100)+'%';let active=D.house.rooms[room]||[];['slotA','slotB'].forEach((id,i)=>{let el=$(id),f=furnitureItems.find(x=>x[0]===active[i]);el.style.display=f?'block':'none';if(f)el.style.backgroundPosition=spritePos(f[1],f[2])});$('furnitureShop').innerHTML=furnitureItems.map(f=>'<div class="furnitureItem"><div class="furnitureThumb" style="background-position:'+spritePos(f[1],f[2])+'"></div><b>'+f[0]+'</b><small>'+(D.house.ownedFurniture.includes(f[0])?'已拥有':f[3]+'金币')+'</small><button onclick="equipFurniture(\''+f[0]+'\')">'+(active.includes(f[0])?'收起':'摆放')+'</button></div>').join('')}
const oldRenderAll=renderAll;renderAll=function(){oldRenderAll();renderHouse()};renderHouse();